export const nepaliData = [
  {
    id: 1,
    type: "greeting",
    en: "Hello",
    npl: "नमस्ते",
    npl_ph: "namaste",
  },
  {
    id: 2,
    type: "phrase",
    en: "Thank you",
    npl: "धन्यवाद",
    npl_ph: "dhanyavaad",
  },
  {
    id: 3,
    type: "phrase",
    en: "Good wishes",
    npl: "शुभकामना",
    npl_ph: "shubhakaamanaa",
  },
  {
    id: 4,
    type: "verb",
    en: "to meet",
    npl: "भेट्नु",
    npl_ph: "bhetnu",
  },
  {
    id: 5,
    type: "verb",
    en: "to visit",
    npl: "घुम्नु",
    npl_ph: "ghumnu",
  },
  {
    id: 6,
    type: "verb",
    en: "to live",
    npl: "बस्नु",
    npl_ph: "basnu",
  },
  {
    id: 7,
    type: "verb",
    en: "to buy",
    npl: "किन्नु",
    npl_ph: "kinnu",
  },
  {
    id: 8,
    type: "verb",
    en: "to ask",
    npl: "सोध्नु",
    npl_ph: "sodhnu",
  },
  {
    id: 9,
    type: "verb",
    en: "to cut",
    npl: "खानु",
    npl_ph: "kaatnu",
  },
  {
    id: 10,
    type: "verb",
    en: "to pay",
    npl: "तिर्नु",
    npl_ph: "tirnu",
  },
  {
    id: 11,
    type: "verb",
    en: "to want",
    npl: "चाहन्नु",
    npl_ph: "chahannu",
  },
  {
    id: 12,
    type: "verb",
    en: "to be able to",
    npl: "सक्नु",
    npl_ph: "saknu",
  },
  {
    id: 13,
    type: "verb",
    en: "to go out",
    npl: "निस्कन्नु",
    npl_ph: "niskannu",
  },
  {
    id: 14,
    type: "verb",
    en: "to shower",
    npl: "नुहाउनु",
    npl_ph: "nuhaaunu",
  },
  {
    id: 15,
    type: "verb",
    en: "to play",
    npl: "खेल्नु",
    npl_ph: "khelnu",
  },
  {
    id: 16,
    type: "verb",
    en: "to wait",
    npl: "कुर्नु",
    npl_ph: "kurnu",
  },
  {
    id: 17,
    type: "verb",
    en: "to get up",
    npl: "उठ्नु",
    npl_ph: "uthnu",
  },
  {
    id: 18,
    type: "verb",
    en: "to sleep",
    npl: "सुत्नु",
    npl_ph: "sutnu",
  },
  {
    id: 19,
    type: "verb",
    en: "to say",
    npl: "भन्नु",
    npl_ph: "bhannu",
  },
  {
    id: 20,
    type: "verb",
    en: "to walk",
    npl: "हिड्नु",
    npl_ph: "hidnu",
  },
  {
    id: 21,
    type: "verb",
    en: "to come",
    npl: "आउनु",
    npl_ph: "aaunu",
  },
  {
    id: 22,
    type: "verb",
    en: "to read",
    npl: "पढ्नु",
    npl_ph: "pardnu",
  },
  {
    id: 23,
    type: "verb",
    en: "to go",
    npl: "जानु",
    npl_ph: "jaanu",
  },
  {
    id: 24,
    type: "verb",
    en: "to speak",
    npl: "बोल्नु",
    npl_ph: "bolnu",
  },
  {
    id: 25,
    type: "verb",
    en: "to take",
    npl: "लिनु",
    npl_ph: "linnu",
  },
  {
    id: 26,
    type: "verb",
    en: "to give",
    npl: "दिनु",
    npl_ph: "dinnu",
  },
  {
    id: 27,
    type: "verb",
    en: "to eat",
    npl: "खान्नु",
    npl_ph: "kaannu",
  },
  {
    id: 28,
    type: "verb",
    en: "to watch",
    npl: "हेर्नु",
    npl_ph: "hernu",
  },
  {
    id: 29,
    type: "verb",
    en: "to make",
    npl: "बनाउनु",
    npl_ph: "banaanu",
  },
  {
    id: 30,
    type: "verb",
    en: "to do",
    npl: "गर्नु",
    npl_ph: "garnu",
  },
  {
    id: 31,
    type: "verb",
    en: "to work",
    npl: "काम गर्नु",
    npl_ph: "kaam garnu",
  },
  {
    id: 32,
    type: "verb",
    en: "to like",
    npl: "मन पर्छ",
    npl_ph: "mana parcha",
  },
  {
    id: 33,
    type: "verb",
    en: "to return",
    npl: "फर्कनु",
    npl_ph: "farkanu",
  },
  {
    id: 34,
    type: "phrase",
    en: "a little bit",
    npl: "अलि अलि",
    npl_ph: "ali ali",
  },
  {
    id: 35,
    type: "phrase",
    en: "to be beautiful",
    npl: "सुन्दर छ",
    npl_ph: "sundara chaa",
  },
  {
    id: 36,
    type: "noun",
    en: "book",
    npl: "किताब",
    npl_ph: "kitaab",
  },
  {
    id: 37,
    type: "noun",
    en: "books",
    npl: "किताबहरु",
    npl_ph: "kitaabharu",
  },
  {
    id: 38,
    type: "noun",
    en: "house",
    npl: "घर",
    npl_ph: "ghar",
  },
  {
    id: 39,
    type: "noun",
    en: "vegetable",
    npl: "तरकारी",
    npl_ph: "takarri",
  },
  {
    id: 40,
    type: "noun",
    en: "uncle",
    npl: "काका",
    npl_ph: "kaka",
  },
  {
    id: 41,
    type: "noun",
    en: "money",
    npl: "पैसा",
    npl_ph: "paisa",
  },
  {
    id: 42,
    type: "noun",
    en: "food",
    npl: "खाना",
    npl_ph: "khana",
  },
  {
    id: 43,
    type: "noun",
    en: "cigarette",
    npl: "चुरोट",
    npl_ph: "churot",
  },
  {
    id: 44,
    type: "noun",
    en: "rest",
    npl: "आराम",
    npl_ph: "aram",
  },
  {
    id: 45,
    type: "adverb",
    en: "sometimes",
    npl: "कहिले कहिँ",
    npl_ph: "kahile kahin",
    tags: ["time"],
  },
  {
    id: 46,
    type: "phrase",
    en: "never",
    npl: "कहिले पनि",
    npl_ph: "kahile pani",
    tags: ["time"],
  },
  {
    id: 47,
    type: "phrase",
    en: "often",
    npl: "प्रायः जस्तो",
    npl_ph: "praaya jaso",
    tags: ["time"],
  },
  {
    id: 48,
    type: "phrase",
    en: "every day",
    npl: "हरेक दिन",
    npl_ph: "harek din",
    tags: ["time"],
  },
  {
    id: 49,
    type: "adverb",
    en: "rarely",
    npl: "विरली",
    npl_ph: "virali",
    tags: ["time"],
  },
  {
    id: 50,
    type: "phrase",
    en: "once a week",
    npl: "हप्ता को एक पटक",
    npl_ph: "hapta ko ek patak",
    tags: ["time"],
  },
  {
    id: 51,
    type: "phrase",
    en: "twice a week",
    npl: "हप्ता को दुई पटक",
    npl_ph: "hapta ko dui patak",
    tags: ["time"],
  },
  {
    id: 52,
    type: "phrase",
    en: "every week",
    npl: "हरेक हप्ता",
    npl_ph: "harek hapta",
    tags: ["time"],
  },
  {
    id: 53,
    type: "adverb",
    en: "after that",
    npl: "त्यसपछि",
    npl_ph: "tyaspchhi",
    tags: ["order of operations"],
  },
  {
    id: 54,
    type: "conjunction",
    en: "and",
    npl: "अनि",
    npl_ph: "ani",
    tags: ["order of operations"],
  },
  {
    id: 55,
    type: "conjunction",
    en: "and",
    npl: "र",
    npl_ph: "ra",
    tags: ["order of operations"],
  },
  {
    id: 56,
    type: "phrase",
    en: "at first",
    npl: "सबै भन्दा पहिले",
    npl_ph: "sabai bhanda pahile",
    tags: ["order of operations"],
  },
  {
    id: 57,
    type: "preposition",
    en: "since/from",
    npl: "देखि",
    npl_ph: "dekhi",
    tags: ["time"],
  },
  {
    id: 58,
    type: "preposition",
    en: "place/from",
    npl: "बाट",
    npl_ph: "baata",
    tags: ["time"],
  },
  {
    id: 59,
    type: "preposition",
    en: "until",
    npl: "सम्म",
    npl_ph: "samma",
    tags: ["time"],
  },
  {
    id: 60,
    type: "noun",
    en: "o'clock",
    npl: "बजे",
    npl_ph: "baje",
    tags: ["time"],
  },
  {
    id: 61,
    type: "preposition",
    en: "at around",
    npl: "तिर",
    npl_ph: "tira",
    tags: ["time"],
  },
  {
    id: 62,
    type: "phrase",
    en: "around this time",
    npl: "बजे तिर",
    npl_ph: "baje tira",
    tags: ["time"],
  },
  {
    id: 63,
    type: "phrase",
    en: "what time",
    npl: "कति बजे",
    npl_ph: "kati baje",
    tags: ["time", "question"],
  },
  {
    id: 64,
    type: "noun",
    en: "time",
    npl: "समय",
    npl_ph: "samaya",
    tags: ["time"],
  },
  {
    id: 65,
    type: "noun",
    en: "morning",
    npl: "बिहान",
    npl_ph: "bihaana",
    tags: ["time"],
  },
  {
    id: 66,
    type: "noun",
    en: "night",
    npl: "राती",
    npl_ph: "ratti",
    tags: ["time"],
  },
  {
    id: 67,
    type: "noun",
    en: "evening",
    npl: "साँझ",
    npl_ph: "samjha",
    tags: ["time"],
  },
  {
    id: 68,
    type: "preposition",
    en: "after",
    npl: "पछि",
    npl_ph: "pacchi",
    tags: ["time"],
  },
  {
    id: 69,
    type: "noun",
    en: "hours",
    npl: "घण्टा",
    npl_ph: "ghantaa",
    tags: ["time"],
  },
  {
    id: 70,
    type: "noun",
    en: "afternoon",
    npl: "दिउँसो",
    npl_ph: "diuso",
    tags: ["time"],
  },
  {
    id: 71,
    type: "preposition",
    en: "with",
    npl: "संग",
    npl_ph: "sanga",
    tags: [],
  },
  {
    id: 72,
    type: "preposition",
    en: "with",
    npl: "संग",
    npl_ph: "sanga",
    tags: [],
  },
  {
    id: 73,
    type: "adverb",
    en: "also",
    npl: "पनि",
    npl_ph: "pani",
    tags: [],
  },
  {
    id: 74,
    type: "adverb",
    en: "a lot",
    npl: "धेरै",
    npl_ph: "dherai",
    tags: [],
  },
  {
    id: 75,
    type: "phrase",
    en: "a lot",
    npl: "एके दम",
    npl_ph: "ake dum",
    tags: [],
  },
  {
    id: 76,
    type: "adjective",
    en: "cold",
    npl: "चिसो",
    npl_ph: "chiso",
    tags: [],
  },
  {
    id: 77,
    type: "conjunction",
    en: "or",
    npl: "अथवा",
    npl_ph: "athawaa",
    tags: [],
  },
  {
    id: 78,
    type: "phrase",
    en: "one moment",
    npl: "एक्का छिन",
    npl_ph: "ekka chhin",
    tags: [],
  },
  {
    id: 79,
    type: "verb",
    en: "understand",
    npl: "बुझ्न",
    npl_ph: "bujhen",
    tags: [],
  },
  {
    id: 80,
    type: "phrase",
    en: "I'm good",
    npl: "सन्चै छ",
    npl_ph: "san chai chaa",
    tags: [],
  },
  {
    id: 81,
    type: "adverb",
    en: "no",
    npl: "होइन",
    npl_ph: "hoina",
    tags: [],
  },
  {
    id: 82,
    type: "adverb",
    en: "yes",
    npl: "हो",
    npl_ph: "ho",
    tags: [],
  },
  {
    id: 83,
    type: "noun",
    en: "child",
    npl: "बच्चा",
    npl_ph: "bacca",
    tags: [],
  },
  {
    id: 84,
    type: "noun",
    en: "father in law",
    npl: "ससुरा",
    npl_ph: "sasura",
    tags: ["family"],
  },
  {
    id: 85,
    type: "noun",
    en: "mother in law",
    npl: "सासु",
    npl_ph: "saasu",
    tags: ["family"],
  },
  {
    id: 86,
    type: "noun",
    en: "wife",
    npl: "श्रीमती",
    npl_ph: "shrimati",
    tags: ["family"],
  },
  {
    id: 87,
    type: "noun",
    en: "younger sister in law",
    npl: "साली",
    npl_ph: "sali",
    tags: ["family"],
  },
  {
    id: 88,
    type: "noun",
    en: "dress",
    npl: "पोसाक",
    npl_ph: "posaaka",
    tags: ["household", "clothes"],
  },
  {
    id: 89,
    type: "noun",
    en: "daughter",
    npl: "छोरी",
    npl_ph: "chori",
    tags: ["family"],
  },
  {
    id: 90,
    type: "noun",
    en: "language",
    npl: "भाषा",
    npl_ph: "bhaasaa",
    tags: [],
  },
  {
    id: 91,
    type: "phrase",
    en: "what's that",
    npl: "के छ",
    npl_ph: "ke cha",
    tags: ["question"],
  },
  {
    id: 92,
    type: "phrase",
    en: "who's that",
    npl: "को छ",
    npl_ph: "ko cha",
    tags: ["question"],
  },
  {
    id: 93,
    type: "pronoun",
    en: "whose",
    npl: "कस्को",
    npl_ph: "kasko",
    tags: ["question"],
  },
  {
    id: 94,
    type: "pronoun",
    en: "which",
    npl: "कुन",
    npl_ph: "kun",
    tags: ["question"],
  },
  {
    id: 95,
    type: "adverb",
    en: "where",
    npl: "कहाँ",
    npl_ph: "kahan",
    tags: ["question"],
  },
  {
    id: 96,
    type: "pronoun",
    en: "to whom",
    npl: "कसलाई",
    npl_ph: "kaslai",
    tags: ["question"],
  },
  {
    id: 97,
    type: "phrase",
    en: "what's that about",
    npl: "के को हो",
    npl_ph: "ke ko ho",
    tags: ["question"],
  },
  {
    id: 98,
    type: "adverb",
    en: "when",
    npl: "कहिले",
    npl_ph: "kahile",
    tags: ["question"],
  },
  {
    id: 99,
    type: "adverb",
    en: "how much",
    npl: "कति",
    npl_ph: "kati",
    tags: ["question"],
  },
  {
    id: 100,
    type: "phrase",
    en: "how many people",
    npl: "कति जना",
    npl_ph: "kati jana",
    tags: ["question"],
  },
  {
    id: 101,
    type: "phrase",
    en: "how many things",
    npl: "कति वटा",
    npl_ph: "kati wota",
    tags: ["question"],
  },
  {
    id: 102,
    type: "adverb",
    en: "why",
    npl: "किन",
    npl_ph: "kina",
    tags: ["question"],
  },
  {
    id: 103,
    type: "pronoun",
    en: "what",
    npl: "के",
    npl_ph: "ke",
    tags: ["question"],
  },
  {
    id: 104,
    type: "pronoun",
    en: "who",
    npl: "को",
    npl_ph: "ko",
    tags: ["question"],
  },
  {
    id: 105,
    type: "phrase",
    en: "who with",
    npl: "को संग",
    npl_ph: "ko sanga",
    tags: ["question"],
  },
  {
    id: 106,
    type: "verb",
    en: "to start",
    npl: "शुरु गर्नु",
    npl_ph: "shuru garnu",
    tags: [],
  },
  {
    id: 107,
    type: "verb",
    en: "to organize",
    npl: "मिलाउनु",
    npl_ph: "milaaunu",
    tags: [],
  },
  {
    id: 108,
    type: "phrase",
    en: "go get",
    npl: "लिन जान्नु",
    npl_ph: "lina jaannu",
    tags: [],
  },
  {
    id: 109,
    type: "verb",
    en: "to iron",
    npl: "इस्त्री गर्नु",
    npl_ph: "istri garnu",
    tags: [],
  },
  {
    id: 110,
    type: "verb",
    en: "to dry",
    npl: "सुकाउनु",
    npl_ph: "sukaaunu",
    tags: [],
  },
  {
    id: 111,
    type: "verb",
    en: "to wash",
    npl: "धुनु",
    npl_ph: "dhunu",
    tags: [],
  },
  {
    id: 112,
    type: "verb",
    en: "to discuss",
    npl: "कुरा गर्नु",
    npl_ph: "kura garnu",
    tags: [],
  },
  {
    id: 113,
    type: "noun",
    en: "story",
    npl: "कथा",
    npl_ph: "kathaa",
    tags: [],
  },
  {
    id: 114,
    type: "verb",
    en: "to fall asleep",
    npl: "निदाउनु",
    npl_ph: "nidaaunu",
    tags: [],
  },
  {
    id: 115,
    type: "verb",
    en: "to wake up",
    npl: "बिउझन्नु",
    npl_ph: "biujhannu",
    tags: [],
  },
  {
    id: 116,
    type: "verb",
    en: "to arrive",
    npl: "पुग्नु",
    npl_ph: "pugnu",
    tags: [],
  },
  {
    id: 117,
    type: "adverb",
    en: "only",
    npl: "मात्र",
    npl_ph: "matra",
    tags: [],
  },
  {
    id: 118,
    type: "adjective",
    en: "late",
    npl: "ढिलो",
    npl_ph: "dhilaa",
    tags: [],
  },
  {
    id: 119,
    type: "adverb",
    en: "again",
    npl: "फेरि",
    npl_ph: "pheri",
    tags: [],
  },
  {
    id: 120,
    type: "conjunction",
    en: "because",
    npl: "किनकी",
    npl_ph: "kinaki",
    tags: [],
  },
  {
    id: 121,
    type: "adverb",
    en: "outside",
    npl: "बाहिर",
    npl_ph: "baahira",
    tags: [],
  },
  {
    id: 122,
    type: "noun",
    en: "dish",
    npl: "भाडा",
    npl_ph: "bhaadaa",
    tags: [],
  },
  {
    id: 123,
    type: "noun",
    en: "market",
    npl: "बजार",
    npl_ph: "bajaar",
    tags: [],
  },
  {
    id: 124,
    type: "adjective",
    en: "another",
    npl: "अर्को",
    npl_ph: "arko",
    tags: [],
  },
  {
    id: 125,
    type: "verb",
    en: "to bring",
    npl: "ल्याउनु",
    npl_ph: "lyaaunu",
    tags: [],
  },
  {
    id: 126,
    type: "verb",
    en: "to wear",
    npl: "लगाउनु",
    npl_ph: "lagaaunu",
    tags: [],
  },
  {
    id: 127,
    type: "noun",
    en: "street",
    npl: "सडक",
    npl_ph: "sadaka",
    tags: [],
  },
  {
    id: 128,
    type: "noun",
    en: "way",
    npl: "बाटो",
    npl_ph: "baato",
    tags: [],
  },
];
